CouponController implementation
bednardev/SportsBettingPlatform pull request #2
Opened 2023-11-20 21:38 UTC by bednardev

2023-11-23 22:03 UTC, kaufdev requested changes

2023-11-23 22:03 UTC, kaufdev commented on src/main/java/com/sbs/services/CouponService.java
> +                    .orElseThrow((() -> new HttpClientErrorException(HttpStatus.NOT_FOUND)));
w wartstwie serwisow nie powinno sie sugerowac skad przyszedl obiekt. NOT_FOUND sugeruje ze to jest restowy kontroller. (a moze byc kolejkanp.). Stworz swoj customowy exception

2023-11-23 22:03 UTC, kaufdev commented on src/main/java/com/sbs/services/CouponService.java
> +    public Optional<Coupon> addBet(Long couponId, Long matchId, String betName) throws CouponInPlayException {
nie musisz tych exceptionow oglaszac tutaj. Tak trzeba robic na pewno gdy sa to checked exceptiony, ale ty masz subklasy Runtime Exceptiona, wiec nie trzeba

2023-11-23 22:03 UTC, kaufdev commented on src/main/java/com/sbs/services/CouponService.java
> +                    .allMatch(bet -> bet.getBetStatus().equals(BetStatus.WON))) {
odwroc warunek. Pierwszy powinien byc zawsze taki ktorego jestes pewien ze istnieje

2023-11-28 16:19 UTC, kaufdev approved these changes

2023-11-28 16:19 UTC, kaufdev commented on src/main/java/com/sbs/models/MatchResult.java
> +public enum MatchResult {
Widzę z ten enum jest w czesto elementem klas która wchodzą lub wychodzą z systemu jako json. W jakiej formie chcesz to mieć na zewnątrz, jako nazwa Enuma czy wartość czyli : "1","x" itp?

2023-11-28 16:19 UTC, kaufdev commented on src/main/java/com/sbs/models/Coupon.java
> +    public Coupon() {
nie musisz takiego kontruktora pisać, bo taki jest defaultowy jesli nie ma innego

2023-11-28 16:19 UTC, kaufdev commented on src/main/java/com/sbs/services/CouponService.java
> +        coupon.setTotalCourse(1F);
przesuń to 1F do stałej klasy

2023-11-28 16:19 UTC, kaufdev commented on src/main/java/com/sbs/services/UserService.java
> +                coupon.setCouponStatus(IN_PLAY);
tu jest userService. Ja bym calą logike ze zmiana czegos w kuponi przerzucil do kuponserwisu. (nacisk na zmiane)

2023-11-28 16:19 UTC, merged

2023-11-28 16:59 UTC, bednardev commented on src/main/java/com/sbs/models/MatchResult.java
> +public enum MatchResult {
Może być jako wartość, tamto jest wprowadzone jako obejście bo ENUM nie pozwala na cyferki

2023-11-28 17:10 UTC, bednardev commented on src/main/java/com/sbs/services/UserService.java
> +                coupon.setCouponStatus(IN_PLAY);
Tylko jak pobranie hajsu zostawimy w userze podczas wysyłania to byśmy CouponService musieli wstrzyknąć do UserService? To ok jest?
No i też jakoś skorelowane by musiały być te metody żeby jednocześnie user wysyłał i zabierało mu hajs i kupon się robił na in_play